export const CONST_CONTENT_TYPE = 'Content-Type';
export const CONST_JSON = 'application/json';
export const CONST_TEXT_PLAIN = 'text/plain';
export const HTTP_SEND_TIME_OUT: number = 60 * 1000;
export const TOPIC_ID = 'topic_id';
export const UPLOAD_LOG_RESOURCE_URI = '/tracklog';
export const MAX_BODY_SIZE = 3 * 1024 * 1024;
export const MAX_BODY_SIZE_ON_HIDE = 32768; // sendBeacon / keepalive
export const MAX_BEACON_REQUEST_IN_PROGRESS = 1;
export const MAX_LOG_COUNT_PER_GROUP = 10000;
